### ISSUE TITLE
fails on windows because of missing repo_location

### ISSUE THREAD

**Issue by spali** [voxpupuli/puppet-telegraf#104]
On windows i get:
```
Error while evaluating a Resource Statement, Class[Telegraf]: parameter 'repo_location' expects a String value, got Undef
```
in the class `params` `repo_location` is not set for windows but is mandatory on class `telegraf`.
I think this was introducted by 1cce2d3e84080098a3ecdd21ba0a155841bc28c7, because defining type `String` it's a mandatory parameter by default.
You should use `Optional[String]` or handle it in the class itself.
As a workaround, I set it to an empty string for windows:
```
repo_location          => ($::kernel) ? { 'windows' => '', default => undef },
```

**Comment by ekohl** [comment]
Fixed in d694f1c16d0ce2e78c1827f83d0bea0f0ebb430e
