### ISSUE TITLE
First voxpopuli release, deprecate yankcrime module on the forge

### ISSUE THREAD

**Issue by SimonHoenscheid** [voxpupuli/puppet-telegraf#107]
Hi everybody, is there already a plan to deprecate the old module on the forge (using the nice "new" deprecation function) and make a first release?

**Comment by alexjfisher** [comment]
@SimonHoenscheid I've made a start.  Hopefully the first Vox release will be sometime this week.

**Comment by dhoppe** [comment]
I am closing this issue because version 2.1.0 of this module was released on 2018-12-29.
