### ISSUE TITLE
Please update package dependencies

### ISSUE THREAD

**Issue by schlitzered** [voxpupuli/puppet-telegraf#118]
please update package dependencies to allow puppet 6.

this means allowing stdlib 6.x.x as well as apt 6.x.x

**Comment by bastelfreak** [comment]
@schlitzered can you provide a patch for this?

**Comment by bastelfreak** [comment]
Ah. This is already implemented in our master branch, just not yet released. https://github.com/voxpupuli/puppet-telegraf/blob/master/metadata.json
