### ISSUE TITLE
[question] Are you open to using inifile instead of toml-rb?

### ISSUE THREAD

**Issue by genebean** [voxpupuli/puppet-telegraf#119]
The telefraf config can easily be managed using inifile resources instead of requiring the toml-rb gem... are you open to a PR for that? I just wanted to check prior to doing the work.

**Comment by bastelfreak** [comment]
Hi. Yes, I think inifile is a better approach for this :)

**Comment by SimonHoenscheid** [comment]
@genebean This sounds interesting, can you give a short hint, how you wabnt to accomplish this using the inifile ressource?

**Comment by dhoppe** [comment]
I would also like to store the variables in ```data/*.yaml``` and use the function ```create_ini_settings()```.

But the file ```telegraf.conf``` is not a real .ini file and the parameters ```indent_width```, ```section_prefix``` and ```section_suffix``` can not work miracles either. 

For example, the input plugin for Jolokia has an additional level. 

I am not sure how this could work.

**Comment by genebean** [comment]
After looking at this more and taking into account all the different things that can be set I have to admit that I actually don't think my initial idea will work. Each of the settings can indeed be created via inifile but making something that works for all the nested options doesn't seem doable in the time I can commit. Sorry :(

**Comment by genebean** [comment]
Ideally we need a standalone toml type and provider for Puppet

**Comment by dhoppe** [comment]
I agree with that. Some plugins use "Array of Tables" and this is really hard to realize with ```inifile```.
