### ISSUE TITLE
Unable able to install previous versions of the module 

### ISSUE THREAD

**Issue by gbjtv** [voxpupuli/puppet-telegraf#125]
Typically when I look to see what versions are available for a puppet module in puppetforge, I can see all previous versions. If you take a look at https://forge.puppet.com/puppet/telegraf it only lists version 2.1.0. Not able to download/install  previous versions with `puppet module install`.

**Comment by alexjfisher** [comment]
You'll find the old versions under the module's original namespace [here](https://forge.puppet.com/yankcrime/telegraf)
