### ISSUE TITLE
Minor: Please fix the (>=5.0.0 < 7.0.0) to (>= 5.0.0 < 7.0.0) in the metadata for dependencies

### ISSUE THREAD

**Issue by ds2000** [voxpupuli/puppet-telegraf#153]
Hi, 
Very minor fix, but please change the `puppetlabs-stdlib (>=5.0.0 < 7.0.0)` to the standard `puppetlabs-stdlib (>= 5.0.0 < 7.0.0)` format.  
We have scripts that scan for module updates and dependencies and I've had to tweak it especially for this ;)

Thanks,
Dave

**Comment by tuxmea** [comment]
@ds2000 what exactly is the issue? a whitespace? which one? in issue title you have a whitespace between >= and the version. In the description you have a whitespace in front of >=

**Comment by ds2000** [comment]
Sorry, man I was tired at the end of yesterday when I wrote that 👍 

It should be >=[[:space:]]5.0.0 < 7.0.0

Thanks.

**Comment by igalic** [comment]
edited the ordinal issue description to hopefully be correct ;)
