### ISSUE TITLE
NO_PUBKEY on Ubuntu | Key has changed

### ISSUE THREAD

**Issue by theo-meow** [voxpupuli/puppet-telegraf#167]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Any
- Ruby: Any
- Distribution: Debian / Ubuntu
- Module version: 1.5.0

## How to reproduce (e.g Puppet code you use)
Apply Module to an Ubuntu 20.04 LTS node.

## What are you seeing
Public Key not available for the repository.

## What behaviour did you expect instead
The pubkey being available.

## Output log
```
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 684A14CF2582E0C5
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Reading package lists...
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: W: GPG error: https://repos.influxdata.com/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 684A14CF2582E0C5
```

## Any additional information you'd like to impart
Seems the key has changed today. On the repos.influxdata.com site, the old key is now "influxdb.key.old".

**Comment by hbenali** [comment]
Should using `05CE15085FC09D18E99EFB22684A14CF2582E0C5` as a key. It is a blocker issue. Thanks
