### ISSUE TITLE
Allow input def without options defined

### ISSUE THREAD

**Issue by jbiel** [voxpupuli/puppet-telegraf#24]
Some of the telegraf inputs don't have many options and have good defaults (haproxy for example.) In the case of these type of modules, it'd be nice to be able to specify an input with just a plugin_type. If options isn't passed the input template fails to apply when it tries to iterate over the empty options hash.

**Comment by yankcrime** [comment]
I'll look into this, but you don't have to use the dedicated `telegraf::input` defined type, you could just do something like:

``` puppet
class { '::telegraf':
  inputs => {
    'haproxy' => {},
  },
}
```

And it will work, e.g:

```
#
# INPUTS:
#
[[inputs.haproxy]]
```
