### ISSUE TITLE
Allow setting groups for the `telegraph` user

### ISSUE THREAD

**Issue by joshuaspence** [voxpupuli/puppet-telegraf#26]
We are running Varnish 4.1 and using the following Telegraf configuration in order to send Varnish stats to InfluxDB:

``` yml
telegraf::inputs:
  exec:
    commands:
      - 'varnishstat -j'
    data_format: 'json'
```

This doesn't quite work for Varnish 4.1, however, because the `telegraf` user is not a member of the `varnish` group. I was able to work around this problem by adding the following puppet code:

```
user { 'telegraf':
  groups     => ['varnish'],
  home       => '/etc/telegraf',
  managehome => false,
  shell      => '/bin/false',
  system     => true,
  require    => Class['varnish::install'],
}
```

It would be more convenient, however, if this module exposed a `$groups` parameter which would allow me to do this:

```
class { 'telegraf':
  groups => ['varnish'],
}
```

Some related resources:
- http://stackoverflow.com/questions/12165818/varnish-cache-log-not-working
- https://github.com/munin-monitoring/contrib/issues/660
- https://github.com/munin-monitoring/contrib/pull/670

**Comment by yankcrime** [comment]
I'm not keen on integrating user or group management in this module.  Personally I don't see anything wrong with the approach taken in your workaround - typically it's the sort of thing you'd apply in a profile class anyway.

If anyone feels strongly enough to disagree to the point where they raise a pull request and argue support for this feature, I'll happily reconsider.
