### ISSUE TITLE
Purge unmanaged files from `/etc/telegraf/telegraf.d`

### ISSUE THREAD

**Issue by joshuaspence** [voxpupuli/puppet-telegraf#39]
Currently this module does not purge unmanaged files from `/etc/telegraf/telegraf.d`. Would it be possible to add this functionality? It looks like this was previously attempted in #21, but that pull request was later abandoned.

**Comment by yankcrime** [comment]
👍 I'll look into this, unless @stuartbfox wants to have another crack.

**Comment by yankcrime** [comment]
Fixed in #43 🎉
