### ISSUE TITLE
File mode on inputs

### ISSUE THREAD

**Issue by maximedevalland** [voxpupuli/puppet-telegraf#64]
I am running into permission issues when using inputs

```
  telegraf::input { 'windows1':
    plugin_type => 'win_perf_counters',
    sections     => {
        'win_perf_counters.object' => {
        'ObjectName'    => 'Network Interface',
        'Counters' => ["Bytes Received/sec","Bytes Sent/sec","Bytes Total/sec","Packets Received/sec","Packets Sent/sec"],
        'Instances' => ["*"],
        'Measurement' => "win_net",
      }
    }
  }
```

It would make more sense to change the mode in [config.pp](https://github.com/datacentred/puppet-telegraf/blob/master/manifests/config.pp#L23) from `0750` to `0770` as, by default, the group manages the file.

This was tested successfully and fixed permission issues.

**Comment by yankcrime** [comment]
A PR for the change would be gratefully received!

**Comment by maximedevalland** [comment]
There you go : #66

**Comment by maximedevalland** [comment]
Merged into master. We can close this issue.
