### ISSUE TITLE
[question] desired merge behavior of $input 

### ISSUE THREAD

**Issue by 7yl4r** [voxpupuli/puppet-telegraf#70]
Currently values passed as `$input` (and $output) [are used as the default to fall back on ](https://github.com/datacentred/puppet-telegraf/blob/master/manifests/init.pp#L160-L161) if a valid hiera hash is not found. 

My expectation was that passing $input or $output directly would _override_ the hiera values (but I'm relatively new to puppet). Is the behavior of these parameters consistent with other puppet modules?

I came across this when looking for a way to modify the hiera data going to the telegraf module so that I don't need to set up a custom fact or implement an ENC for an "arbitrary" subset of nodes.

**Comment by alexjfisher** [comment]
Ability to configure merge behaviour was added in https://github.com/voxpupuli/puppet-telegraf/pull/134
Hopefully this should meet your needs.  I'll close this ticket, but please reopen if you're still having issues.
