### ISSUE TITLE
Telegraf installation not going through.

### ISSUE THREAD

**Issue by dichque** [voxpupuli/puppet-telegraf#72]
Find these errors while running puppet agent
Execution of '/usr/bin/yum -d 0 -e 0 -y list telegraf' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: influxdata. Please verify its path and try again

**Comment by yankcrime** [comment]
@dichque Are you still seeing this problem?

**Comment by yankcrime** [comment]
Closing under suspicion that this was a transient, temporary issue to do with upstream repository availability.
