### ISSUE TITLE
Influxdb changed their repo structure for RHEL?

### ISSUE THREAD

**Issue by HristoMohamed** [voxpupuli/puppet-telegraf#77]
baseurl=https://repos.influxdata.com/rhel/$releasever/$basearch/stable
 python -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'
Loaded plugins: kernel-module, priorities, protectbase, versionlock
{'arch': 'ia32e',
 'basearch': 'x86_64',
 'releasever': '6.7',
}

For CC7 the releasever is 7, inspite of the release
This can be corrected if on line 32 in install.pp we change the $releasever with for example 
${facts['os']['release']['major']

**Comment by yankcrime** [comment]
@HristoMohamed Is this still a problem?  Can you raise a PR with the proposed change if so, thanks.

**Comment by dhoppe** [comment]
I am closing this ticket due to lack of feedback.
