### ISSUE TITLE
Upgrading telegraf version does not trigger telegraf service restart

### ISSUE THREAD

**Issue by sparr** [voxpupuli/puppet-telegraf#86]
If I change `telegraf::ensure` in my configuration to specify a version, that version gets installed but the service doesn't restart.

**Comment by sparr** [comment]
This may be caused by `$service_restart      = 'pkill -HUP telegraf'` which just has the service reload its config rather than actually restarting.

**Comment by lobeck** [comment]
This is not an issue on Ubuntu, as apt/dpkg will trigger the restart.

**Comment by yankcrime** [comment]
Closing as this is an upstream / packaging issue.
