### ISSUE TITLE
Dependency on toml-rb bumps ruby version requirement

### ISSUE THREAD

**Issue by sparr** [voxpupuli/puppet-telegraf#91]
Was this intentional or even discussed prior to merging #80? toml-rb requires Ruby 1.9 (and didn't say so, until I filed an issue on it), which means that puppet-telegraf now requires Ruby 1.9

**Comment by sparr** [comment]
I am currently jumping through the requisite hoops to get it working on my older Ruby environments, which means installing backports and a few other steps. I'm sure no one else has this problem, but I wanted to at least mention it for posterity.

**Comment by yankcrime** [comment]
Thanks @sparr and apologies - support for anything _older_ than 1.9 hadn't even crossed my mind, let alone been up for discussion.

**Comment by yankcrime** [comment]
I've tagged a new release and it's called out in the readme as a requirement.
