### ISSUE TITLE
New array format for input/output definition in hiera requires polluting configs

### ISSUE THREAD

**Issue by sparr** [voxpupuli/puppet-telegraf#94]
Inputs and outputs (and aggregators if I ever get a PR ready for that) that previously had no configuration no longer work.

`cpu:` was previously enough to create a cpu input. Now `cpu:` fails because telegraf.conf.erb:80 expects it to contain an array, and `cpu: []` fails because the first element of that array is expected to be a hash. I find myself having to do some nonsense like this:

    cpu:
      - placeholderkey: placeholdervalue

which of course ends up polluting my actual telegraf.conf with those placeholders.

If there's a better way to make this work with the new code from #80, I would love to know. If there's not, this seems severe enough to be a bug in need of fixing, and maybe fixing it would also address the minor annoyance of old configs not working with the new code; it would be nice if the code recognized a bare hash as functionally identical to an array containing one hash.

**Comment by sparr** [comment]
To say it another way... I cannot come up with a hiera yaml config that produces this telegraf.conf snippet:

    [[inputs.cpu]]
    
    [[inputs.mem]]

**Comment by nrdmn** [comment]
Please see the example form the readme. You can write
```
mem: [{}]
```
to get
```
[[inputs.mem]]
```

**Comment by sparr** [comment]
Was there some rationale for not supporting the old formats? There doesn't even seem to be any ambiguity.

**Comment by nrdmn** [comment]
According to the [toml specification](https://github.com/toml-lang/toml), the old format is not the correct yaml representation of telegraf's toml config.
